# Generated by ChatGPT patch

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_visible_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='출근 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='퇴근 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_records', to=settings.AUTH_USER_MODEL, verbose_name='근무자')),
            ],
            options={
                'verbose_name': '근무 기록',
                'verbose_name_plural': '근무 기록',
                'ordering': ['-started_at'],
            },
        ),
    ]
