# Generated by WelfareON v1.0.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField('물품 위치', blank=True, max_length=120),
        ),
    ]
